### ISSUE TITLE
Satyam Kumar, 1st Year (2017-21), 39/CSE/17078/276

### ISSUE THREAD

**Issue by Satyam-TG** [IIITKalyaniFOSC/design-jam#2]

**Comment by satyamtg** [comment]
# My Submission
There are 5 variants of my logo.
![Dark Play](https://raw.githubusercontent.com/IIITKalyaniFOSC/design-jam/2018/submissions/Satyam-TG/raster_png/fosc_dark_play.png)
![Light Play](https://raw.githubusercontent.com/IIITKalyaniFOSC/design-jam/2018/submissions/Satyam-TG/raster_png/fosc_light_play.png)
![Dark](https://raw.githubusercontent.com/IIITKalyaniFOSC/design-jam/2018/submissions/Satyam-TG/raster_png/fosc_dark.png)
![Light](https://raw.githubusercontent.com/IIITKalyaniFOSC/design-jam/2018/submissions/Satyam-TG/raster_png/fosc_light.png)
![Black](https://raw.githubusercontent.com/IIITKalyaniFOSC/design-jam/2018/submissions/Satyam-TG/raster_png/fosc_black.png)
## What the logo means ?
The various rounded rectangles (lke the material design chips), of which the "FOSC" is composed of, represent the different chunks of code in order to make an application. At the bottom, one can see a misspelt "IIIT Kalyani". This contains the special characters mostly used in development and represents the fact that the FOSC is for people who code. The angular brackets are there to give a feel of an HTML tag. This represents the way we started the FOSC, by building websites. The coloured chips in the play version represent syntax highlighting. This gives an extra geeky feel to the logo.

## Why the variants ?
There are variants so that the logo can be used on every type of background (dark and light). The dark version is for light backgrounds and the light one is for dark backgrounds. And for the black one, well, we can use black even in B/W websites/ papers etc. All the logos except the black one is "Material Design" compliant and are made to give a flatter feel.

## About Me
Name : __Satyam Kumar__  
Current Year : __1st Year (2017-2021)__ 

## Image Types Supplied :  

- [x] Vector Images - Illustrator native *.ai files and web compatible *.svg files
- [x] Raster Images - High resolution *.png files
  
## Download Link:
  * [Folder with all file types](https://github.com/IIITKalyaniFOSC/design-jam/tree/2018/submissions/Satyam-TG)

**Comment by anubhavp28** [comment]
@Satyam-TG Inspiring, you really have put a lot of effort into this. Thanks man!
